cls: ctrl_td3
discount: 0.99

tau: 1.0 # hard update
actor_update_freq: 1
target_update_freq: 250

critic_hidden_dims: [512, 512, 512] # this is actually not used
actor_hidden_dims: [512, 512, 512]

critic_lr: 0.0003
actor_lr: 0.0003

target_policy_noise: 0.2
noise_clip: 0.3
exploration_noise: 0.2
normalize_obs: false

# below are params specific to ctrl_td3
feature_dim: 256
feature_lr: 0.0001
phi_hidden_dims: [512, 512]
mu_hidden_dims: [512, 512]
theta_hidden_dims: [512, ]
reward_coef: 1.0
feature_update_ratio: 1
temperature: 0.1
critic_hidden_dim: 512
reward_hidden_dim: 512
back_critic_grad: false
critic_coef: 1.0
