cls: diffsr_td3
discount: 0.99

tau: 0.005 # soft update
actor_update_freq: 1
target_update_freq: 1

critic_hidden_dims: [512, 512, 512] # this is actually not used
actor_hidden_dims: [512, 512, 512]

critic_lr: 0.0003
actor_lr: 0.0003

target_policy_noise: 0.2
noise_clip: 0.3
exploration_noise: 0.2

# below are params specific to diffsr_td3
x_min: -10.0
x_max: 10.0
sample_steps: 50
beta_min: 0.0001
beta_max: 0.02
s: 0.008
noise_schedule: vp

feature_update_ratio: 1
feature_dim: 512
latent_dim: 256
embed_dim: 128
psi_hidden_dims: [256, 256]
zeta_hidden_dims: [256, 256]
critic_hidden_dim: 1024
reward_hidden_dim: 1024
encoder_hidden_dims: [256, 256]
decoder_hidden_dims: [256, 256]

vae_lr: 0.0003
diffusion_lr: 0.0003

use_latent: false
recon_coef: 1.0
kl_coef: 1.0
diffusion_coef: 1.0
reward_coef: 0.1
critic_coef: 1.0
back_critic_grad: false
