cls: lvrep_td3
discount: 0.99

tau: 0.005 # hard update
actor_update_freq: 2
target_update_freq: 1

critic_hidden_dims: [512, 512, 512] # this is actually not used
actor_hidden_dims: [512, 512, 512]

critic_lr: 0.0003
actor_lr: 0.0003

target_policy_noise: 0.2
noise_clip: 0.3
exploration_noise: 0.2

# below are params specific to lvrep_td3
feature_dim: 256
feature_tau: 0.005 # hard update
use_feature_target: true
feature_update_ratio: 1
encoder_hidden_dims: [256, 256]
decoder_hidden_dims: [256, 256]
f_hidden_dims: [256, 256]
feature_lr: 0.0003
critic_hidden_dim: 512
num_noise: 20
