cls: sac
discount: 0.99
tau: 0.005
alpha: 0.2
auto_entropy: true

target_update_freq: 2

critic_hidden_dims: [1024, 1024]
actor_hidden_dims: [1024, 1024]

critic_lr: 0.0001
actor_lr: 0.0001
alpha_lr: 0.0001
