cls: td3
discount: 0.99

tau: 1.0 # hard update
actor_update_freq: 2
target_update_freq: 250

critic_hidden_dims: [512, 512, 512]
actor_hidden_dims: [512, 512, 512]

critic_lr: 0.0003
actor_lr: 0.0003

target_policy_noise: 0.2
noise_clip: 0.3
exploration_noise: 0.2
